image: alpine/edge
packages:
  - go
  - hugo
  - hut
  - openring
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~sircmpwn/drewdevault.com
triggers:
  - action: email
    condition: always
    to: Drew DeVault <drew@ddevault.org>
tasks:
- build: |
    cd drewdevault.com
    openring \
      -s https://os.phil-opp.com/rss.xml \
      -s https://aphyr.com/posts.atom \
      -s https://sourcehut.org/blog/index.xml \
      -s https://100r.co/links/rss.xml \
      -s https://blog.brixit.nl/rss/ \
      -s https://bitfehler.srht.site/index.xml \
      -s https://www.willowbarraco.fr:443/atom.xml \
      -s https://torresjrjr.com/archive/index.xml \
      -s https://cadence.moe/blog/rss.xml?limit=30 \
      -s https://harelang.org/blog//index.xml \
      -s https://vladh.net/index.xml \
      < webring-in.template \
      > layouts/partials/webring-out.html
    hugo
- upload: |
    cd drewdevault.com
    hut pages publish -d drewdevault.com ./public/
