image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- curl
- zig
sources:
- https://git.sr.ht/~sircmpwn/drewdevault.com
tasks:
- zine: |
    # TODO: Build from source (or install an Alpine package)
    curl https://redacted.moe/f/f4b9d9a6 > zine
    sudo cp zine /usr/bin/
- build: |
    cd drewdevault.com
    zine release
- publish: |
    hut pages publish -d drewdevault.com public/
triggers:
  - action: email
    condition: always
    to: Drew DeVault <drew@ddevault.org>
