image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- zine
sources:
- https://git.sr.ht/~sircmpwn/drewdevault.com
tasks:
- build: |
    cd drewdevault.com
    zine release
- publish: |
    cd drewdevault.com
    hut pages publish -d drewdevault.com public/
triggers:
  - action: email
    condition: always
    to: Drew DeVault <drew@ddevault.org>
