baseURL = "https://drewdevault.com/"
title = "Drew DeVault's blog"
pygmentsUseClasses = true
uglyurls = true
disablePathToLower = true
rssLimit = 10

[permalinks]
blog = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true

[services]
[services.rss]
limit = -1
